### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by BUAAers** [wszlong/sb-nmt#5]
@wszlong 学长您好，我有个问题想请教一下（我就用中文描述了）

在执行 ./datagen.sh处理数据时，根据sh文件默认已经得到了source和target语料的  bpe分词语料  和  bpe词表 。然后在程序generator_utils.py中有个函数
def translation_token_generator(data_dir, tmp_dir, train_src_name, train_tgt_name, vocab_src_name, vocab_tgt_name):
    train_src_path = os.path.join(tmp_dir, train_src_name)
    train_tgt_path_l2r = os.path.join(tmp_dir, train_tgt_name + ".l2r")
    train_tgt_path_r2l = os.path.join(tmp_dir, train_tgt_name + ".r2l")
    token_vocab_src_dir = os.path.join(data_dir, vocab_src_name)
    token_vocab_tgt_dir = os.path.join(data_dir, vocab_tgt_name)

这里train_tgt_path_l2r 和train_tgt_path_r2l 是不是表明在执行 ./datagen.sh前，target其实有2个文件，而train_tgt_name只是共同前缀，但他们共享同一个bpe词表。

假如我的train_tgt_path_l2r 文件语料为：
A Republic@@ an strategy to counter the re-@@ election of Obama
那么我的train_tgt_path_r2l 文件对应的语料为：
Obama of election re-@@ the counter to strategy  an Republic@@ A

请问是这个意思吗？

**Comment by BUAAers** [comment]
或者说其实都是正常语序，只是train_tgt_path_l2r 分别是由2个独立的翻译系统（从左到右，从右到左）得到的，就像下面这个
source：他们 正在 研制 一种 超大型 的 叫做 炸弹水母
L2R:  they are developing a super , big , mother , called the bomb .
R2L:  they are working on a much larger mother，called the mother of a bomb.

**Comment by wszlong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi,train_tgt_name 是目标端训练语料共同的前缀，假设train_tgt_name="train.tgt"，那么目标端两个方向的语料为：“train.tgt.l2r”和“train.tgt.r2l”。另外，假设训练集为(x, y),目标端反向的目标语言表示为y_r。 首先训练一个目标端从左到右的模型（l2r）和目标端从右到左的模型（r2l）, 然后使用这两个模型 分别翻译训练集的源语言，生成伪的目标语言l2r_p, r2l_p。然后组合成两个三元组（（x, y, r2l_p）, (x, l2r_p, y_r) ），合并起来去训练SBNMT。祝好！周龙
    
        
            
        
    
    
        
        

        
    

    在2019年11月4日 17:02，BUAAers<notifications@github.com> 写道： 


@wszlong 学长您好，我有个问题想请教一下（我就用中文描述了）

在执行 ./datagen.sh处理数据时，根据sh文件默认已经得到了source和target语料的  bpe分词语料  和  bpe词表 。然后在程序generator_utils.py中有个函数

def translation_token_generator(data_dir, tmp_dir, train_src_name, train_tgt_name, vocab_src_name, vocab_tgt_name):

train_src_path = os.path.join(tmp_dir, train_src_name)

train_tgt_path_l2r = os.path.join(tmp_dir, train_tgt_name + ".l2r")

train_tgt_path_r2l = os.path.join(tmp_dir, train_tgt_name + ".r2l")

token_vocab_src_dir = os.path.join(data_dir, vocab_src_name)

token_vocab_tgt_dir = os.path.join(data_dir, vocab_tgt_name)

这里train_tgt_path_l2r 和train_tgt_path_r2l 是不是表明在执行 ./datagen.sh前，target其实有2个文件，而train_tgt_name只是共同前缀，但他们共享同一个bpe词表。

假如我的train_tgt_path_l2r 文件语料为：

A Republic@@ an strategy to counter the re-@@ election of Obama

那么我的train_tgt_path_r2l 文件对应的语料为：

Obama of election re-@@ the counter to strategy  an Republic@@ A

请问是这个意思吗？

**Comment by Shajiu** [comment]
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    tf.app.run()
  File "/home2/sj/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run.py", line 96, in main
    train_steps=FLAGS.train_steps)
  File "/home2/sj/translation/sb-nmt-master/utils/trainer_utils.py", line 135, in run
    features, labels = train_input_fn()
  File "/home2/sj/translation/sb-nmt-master/utils/trainer_utils.py", line 416, in input_fn
    examples = text_reader.input_pipeline(data_file_patterns[0], capacity, mode)
  File "/home2/sj/translation/sb-nmt-master/utils/text_reader.py", line 176, in input_pipeline
    data_items_to_decoders=data_items_to_decoders)
  File "/home2/sj/translation/sb-nmt-master/utils/text_reader.py", line 131, in examples_queue
    data_files = tf.contrib.slim.parallel_reader.get_data_files(data_sources)
  File "/home2/sj/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/data/parallel_reader.py", line 304, in get_data_files
    data_files += get_data_files(source)
  File "/home2/sj/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/data/parallel_reader.py", line 311, in get_data_files
    raise ValueError('No data files found in %s' % (data_sources,))
ValueError: No data files found in data_dir/wmt_ende_bpe32k-train*
出现这个“wmt_ende_bpe32k-train*”又是什么文件呢？谢谢

**Comment by wszlong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            
        
    你好，”wmt_ende_bpe32k“是一个文件的前缀（因为在原始t2t 英德代码上改的，未做统一），只需将 wmt_ende_bpe32k-train* 和data_dir目录下生成的文件对应上即可。（改动前缀在 utils/text_reader.py的函数 get_datasets）。祝好！周龙
    
        
        

        
    

    在2019年12月13日 14:51，shajiu<notifications@github.com> 写道： 


Traceback (most recent call last):

File "run.py", line 99, in 

tf.app.run()

File "/home2/sj/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run

_sys.exit(main(argv))

File "run.py", line 96, in main

train_steps=FLAGS.train_steps)

File "/home2/sj/translation/sb-nmt-master/utils/trainer_utils.py", line 135, in run

features, labels = train_input_fn()

File "/home2/sj/translation/sb-nmt-master/utils/trainer_utils.py", line 416, in input_fn

examples = text_reader.input_pipeline(data_file_patterns[0], capacity, mode)

File "/home2/sj/translation/sb-nmt-master/utils/text_reader.py", line 176, in input_pipeline

data_items_to_decoders=data_items_to_decoders)

File "/home2/sj/translation/sb-nmt-master/utils/text_reader.py", line 131, in examples_queue

data_files = tf.contrib.slim.parallel_reader.get_data_files(data_sources)

File "/home2/sj/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/data/parallel_reader.py", line 304, in get_data_files

data_files += get_data_files(source)

File "/home2/sj/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/data/parallel_reader.py", line 311, in get_data_files

raise ValueError('No data files found in %s' % (data_sources,))

ValueError: No data files found in data_dir/wmt_ende_bpe32k-train*

出现这个“wmt_ende_bpe32k-train*”又是什么文件呢？谢谢
